### ISSUE TITLE
libc++.1.0.dylib no such file

### ISSUE THREAD

**Issue by gavr123456789** [madlib-lang/madlib#67]
## Symptoms:

Cant run madlib compiler

## Reproduction instructions

```shell
madlib -i "mad.mad" -o "outputFolder"
dyld[12935]: Library not loaded: /usr/local/opt/llvm-9/lib/llvm-9/lib/libc++.1.0.dylib
  Referenced from: /opt/homebrew/lib/node_modules/@madlib-lang/madlib/node_modules/binary-install/bin/madlib
  Reason: tried: '/usr/local/opt/llvm-9/lib/llvm-9/lib/libc++.1.0.dylib' (no such file), '/usr/local/lib/libc++.1.0.dylib' (no such file), '/usr/lib/libc++.1.0.dylib' (no such file)

```

**Additional context**
OS: mac os
processor: m1
clang version output:
```
clang --version
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: arm64-apple-darwin21.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
Also there are no opt in usr/local
```
home> cd /usr/local/
/u/local> ls
bin
```

**Comment by aboeglin** [comment]
@gavr123456789 
The arm64 build for mac os is not published yet. What you're seeing I guess is that it's looking for a libc++ for x64, which it does not find on a m1. I do most of the development on a m1 macbook so it definitely works and I intended to publish a release for it. I'll get to that soon and keep you updated!

**Comment by aboeglin** [comment]
There's MadUI that's being ported to the new `0.12.0` version. Madlib has native support for *almost-jsx*. It's not named yet but it's probably end up being called madx. The main difference is in how children are handled, given how the type system works it was too stretched to allow for certain things. Still trying to figure out the right sweet spot between practical and logical. The documentation renderer is built with it. At a high level it's closer to the Elm architecture or Hyperapp if you heard about it. Otherwise it's mostly like react but with stateless functional components only and a global state close to redux. Each event handler is a function of the global state that resembles a reducer.

I'm currently about to wrap up a `0.12.1` fixing a few things I'll try to ship that tomorrow night, along with the arm64 build for mac os, given tests succeed.

Code for the documentation UI can be found here: https://github.com/madlib-lang/maddoc. Although it probably does not run with the newer version as `0.12.0` brought a few breaking changes. I'm still in the process of updating all packages but before that a needed patch version is needed as that will fix a few things that came up short after the latest release.

**Comment by aboeglin** [comment]
I finally managed to wrap up the release. The version `0.12.1` should work. If not I'm happy to assist you further.

**Comment by gavr123456789** [comment]
Now I can actually run it, but got error
File:  
```
import IO from "IO"

IO.putLine("Hello World !")
```

Error: 
```
madlib run mad.mad 
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/Users/gavr/Documents/Projects/madlib/.run/mad.mjs'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v17.6.0
madlib: callCommand: node .run/mad.mjs  (exit 1): failed
```

**Comment by aboeglin** [comment]
I’ll try to reproduce that. My first thought would be that it got confused with with the file name. What is the content of the .run folder?

**Comment by gavr123456789** [comment]
<img width="631" alt="image" src="https://user-images.githubusercontent.com/30507409/163548587-8c4c73e2-b5ce-4d4e-840e-267ede07de40.png">

**Comment by gavr123456789** [comment]
renamed file, and gotsame error

**Comment by aboeglin** [comment]
I figured it out, it's because you run it from the same folder. Not saying that's wrong, but so far the sources were always located in some src folder of some sort and madlib was run from outside of it. I'll release a fix for that later.

**Comment by aboeglin** [comment]
@gavr123456789 Also another short question, did you install anything specific for libc++ to be available or you only installed the new version via npm? I have a similar issue reported for x64.

**Comment by gavr123456789** [comment]
I didnt install any new native package, all I did is run again npm install madlib, but I have clang installed.

**Comment by aboeglin** [comment]
Yeah, clang comes with macos. Well, weirdly the rpath is not complete for x64. I think I have a fix for it now. I'll release `0.12.2` later with these few fixes.

**Comment by aboeglin** [comment]
`0.12.2` released. Your above attempt should now work fine.

**Comment by gavr123456789** [comment]
yaay, thanks  
<img width="443" alt="image" src="https://user-images.githubusercontent.com/30507409/163626801-352acc92-518f-492d-bcd6-d74ccdefcb00.png">
